### PR TITLE
add feature name from DisplayFusion

### PR DESCRIPTION
**Pull request by graingert**
DisplayFusion lists this feature as "Prevent mouse from snagging on unaligned screen edges, add this feature name to the readme to make searching for LittleBigMouse easier

### CODE REVIEW

**Comment by gribuser** [comment]
How did you manage to build LittleBigMouse, @graingert ? What's this HLab.* stuff, where did you get it?

**Comment by graingert** [comment]
@gribuser HLab?

**Comment by gribuser** [comment]
Yes. When I try to build LittleBigMouse it requires a long list of HLab libs. Google helps not :(.
What's this thing, where do you get it? I want to fix #80 but can't even start.

**Comment by graingert** [comment]
@gribuser I think you meant to message @mgth ?

**Comment by gribuser** [comment]
Unfortunately, it looks like he is not going to answer any time soon. This project seem to be simply abandoned for several months by now.
But I see you have this pull request, so I assume you have at least successfully built this app. Which neither I nor anyone I know can do.
So you are the only hope universe has for today. Did you managed to build this LittleBigMouse? Where did you get HLab? As I assume from the license this should be some open source stuff.
But it's not there :(

**Comment by mgth** [comment]
Sorry about the long delay,
I've been working on another project this year, but no, LBM is not abandonned.
I hope I'll can take some time by the end of the year to post a new version, with the missing libs (they are part of my current project and could not be published before the end of this one)

A problem I got for now is HLab project have been ported to .Net 5 and some change are needed for compatibility, but it's almost done.

**Comment by gribuser** [comment]
Wow.
Is there any way we can get #80 fixed say, in a week or two, @mgth ? This little issue drives the complex and totally amazing app completely useless for many people, including me.
I can pay, if nothing else :)

**Comment by polykoma** [comment]
Would also love to see a fix for issue#80 <3  Thank you for your time.  Willing to donate aswell 👍

**Comment by JonWillis-Tote** [comment]
I just pulled down the code to have a look at fixing the duplicate monitor issue too, as i bought 2x4k monitors, but as they are the same brand LBM detects it as one, but as above i can't build it. Work around was to connect one as DisplayPort and the other as HDMI, but both on DisplayPort merge into 1 from LBM point of view.
Would be great to have the HLab libraries once you can make them publicly available so it can be resolved.

**Comment by JonathanWillis** [comment]
I just pulled down the code to have a look at fixing the duplicate monitor issue too, as i bought 2x4k monitors, but as they are the same brand LBM detects it as one, but as above i can't build it. Work around was to connect one as DisplayPort and the other as HDMI, but both on DisplayPort merge into 1 from LBM point of view.
Would be great to have the HLab libraries once you can make them publicly available so it can be resolved.

**Comment by wickedlizerd** [comment]
> Unfortunately, it looks like he is not going to answer any time soon. This project seem to be simply abandoned for several months by now.
> But I see you have this pull request, so I assume you have at least successfully built this app. Which neither I nor anyone I know can do.
> So you are the only hope the universe has for today. Did you managed to build this LittleBigMouse? Where did you get HLab? As I assume from the license this should be some open source stuff.
> But it's not there :(

Most of hlab can now be found [here](https://github.com/CHMP-HLab/HLab)
A few dependencies are missing, but you can find precompiled versions of them in your LittleBigMouse installation directory.

**Comment by strazto** [comment]
As of recent commits, this and #148 should be fully resolved, unless I missed something in the commit history

**Pull request closed without merging**
